### PR TITLE
Feature 150 typo markdownmd

### PR DESCRIPTION
**Pull request by Noggi36**
Feel free to merge. Thanks in advance.

### CODE REVIEW

**Review by PSpindler — APPROVED** [review]
Sieht sauber aus, danke :)

**Comment by Noggi36** [comment]
Unfortunately merged direct with master. Is that a problem?

**Comment by JohannesBru** [comment]
Merging directly into master is a problem as other people working in the Repo will always pull the most up to date dev and branch off from there. Your feature will not be in their Lokal branch as it is implemented in master. This may lead to merge conflicts.

Moreover you might break a working version on master. Usually master is not touched until development works on dev are done, tested and in working condition. Then dev gets merged into master.

**Comment by JohannesBru** [comment]
@Noggi36 i will Revert the merge into master. Should restore master.

**Pull request merged**
