### PR TITLE
added-branching-model-information-186

### PR DESCRIPTION
**Pull request by LinoEsra**
Added further information about the Branching-Model

### CODE REVIEW

**Comment by LinoEsra** [comment]
Please review!

**Comment by LinoEsra** [comment]
Please Review!

**Review by KevDitt — CHANGES_REQUESTED** [review]
Looks great despite "modell" is spelled wrong.... it's "model"

**Comment by LinoEsra** [comment]
Fixed Typos. Please review again :)

**Review by NJReith — APPROVED** [review]
looks good to me :)

**Review by KevDitt — APPROVED** [review]
Now it looks good :)

**Review by benjaminkrahn — APPROVED** [review]
Cant find any issues with the commit. Looks good to me.  
ps. very helpful link!

**Pull request closed without merging**
