### PR TITLE
added PV-weblinks.md and filled with websources #32

### PR DESCRIPTION
**Pull request by FaidoEwald**
### I made new file "PV_weblinks.md" out of "PV_EFH_Literaturlinks.txt"...

... and filled it with some more data:
- PV-Onlinetools: PVGIS, Sonnenverlauf.de und **k2-Base**
- SonnJa! Weblink to the project on einleuchtend.org

there will be a second file (git_weblinks.md) soon, which contains the left information about git.

### Please contribute and put interesting PV_weblinks for engineers!

### CODE REVIEW

**Comment by FaidoEwald** [comment]
### I made new file "git_weblinks.md" out of "PV_EFH_Literaturlinks.txt"...
... and slightly modified the description lines.

Are you fine with that @PhuongThaoBui ? And the others?

**Comment by PhuongThaoBui** [comment]
The content is good. There are some small change to make it even better.
The URL in markdown you can also organize all your links like this: [http:example.c­om] instead of { http:example.com}.
Markdown supports that: Title:␣␣␣␣MultiMarkdown-CheatSheet␣␣⏎ and Date:␣␣␣␣␣2014-01-28␣␣⏎ and Author:␣␣␣Mark Down, Mac Andi␣␣⏎ 
You can try it next time

**Comment by FaidoEwald** [comment]
> 
> 
> I like these changes, but I don't know if adding another file (your BibTex) will be easy to combine into the old "shared_literature.bib"
> Probably you will have to solve a merge conflict there

I think this is what I have to do then :) 
It was LH's proposal to put it in there as you can see in his comment above(!)

**Comment by FaidoEwald** [comment]
> 
> 
> The content is good. There are some small change to make it even better.
> The URL in markdown you can also organize all your links like this: [http:example.c­om] instead of { http:example.com}.
> Markdown supports that: Title:␣␣␣␣MultiMarkdown-CheatSheet␣␣⏎ and Date:␣␣␣␣␣2014-01-28␣␣⏎ and Author:␣␣␣Mark Down, Mac Andi␣␣⏎
> You can try it next time

Thank you. I'll definitely do that. In which part/file do you mean? The git_literature.md?

**Comment by FaidoEwald** [comment]
@TheBlackBlade thanks for your approval. Ready to go...

**Comment by PhuongThaoBui** [comment]
> ### I made new file "git_weblinks.md" out of "PV_EFH_Literaturlinks.txt"...
> ... and slightly modified the description lines.
> 
> Are you fine with that @PhuongThaoBui ? And the others?



> ### I made new file "git_weblinks.md" out of "PV_EFH_Literaturlinks.txt"...
> ... and slightly modified the description lines.
> 
> Are you fine with that @PhuongThaoBui ? And the others?

Sure 👍🏻

**Pull request merged**
